# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculadora_responsive.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QPixmap, QIcon
from PyQt5.QtWidgets import QGridLayout, QVBoxLayout
from PyQt5.QtCore import QByteArray
from PyQt5.QtSvg import QSvgWidget
import sys 
import sympy as sym
import numpy as np
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg, NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure
from matplotlib.backends.backend_svg import *
import matplotlib.pyplot as plt
from io import BytesIO
from icons import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 500)
        icon = iconodesdeBase64(ICONCALCU)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_izquierdo = QtWidgets.QFrame(self.centralwidget)
        self.frame_izquierdo.setMinimumSize(QtCore.QSize(350, 500))
        self.frame_izquierdo.setMaximumSize(QtCore.QSize(350, 15777215))
        self.frame_izquierdo.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(13, 156, 208, 241), stop:1 rgba(255, 255, 255, 255));")
        self.frame_izquierdo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_izquierdo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_izquierdo.setObjectName("frame_izquierdo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_izquierdo)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_izquierdo)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_3.setStyleSheet("QLabel{ \n"
"background-color: rgb(252, 252, 252);\n"
"border-color: rgb(251, 231, 255);\n"
"border: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_entrada = QtWidgets.QLabel(self.frame_3)
        self.label_entrada.setText("")
        self.label_entrada.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_entrada.setObjectName("label_entrada")
        self.verticalLayout_3.addWidget(self.label_entrada)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_izquierdo)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame_4.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(164, 188, 211, 0), stop:0.971591 rgba(255, 255, 255, 0));\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_6.setStyleSheet("QPushButton{\n"
"  padding: .375rem .75rem;\n"
"  border: 1px solid #00244b;\n"
"  border-radius: .25rem;\n"
"  color: #00244b;\n"
"  transition: color .15s ease-in-out,\n"
"  background-color .15s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #bed7e0;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.button_x = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("x"))
        self.button_x.setMaximumSize(QtCore.QSize(90, 50))
        self.button_x.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_x.setShortcut("")
        self.button_x.setObjectName("button_x")
        self.gridLayout.addWidget(self.button_x, 0, 0, 1, 1)
        self.button_y = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("y"))
        self.button_y.setMaximumSize(QtCore.QSize(90, 50))
        self.button_y.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_y.setObjectName("button_y")
        self.gridLayout.addWidget(self.button_y, 0, 1, 1, 1)
        self.button_exp = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("^"))
        self.button_exp.setMaximumSize(QtCore.QSize(90, 50))
        self.button_exp.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_exp.setObjectName("button_exp")
        self.gridLayout.addWidget(self.button_exp, 0, 2, 1, 1)
        self.button_sin = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("sin("))
        self.button_sin.setMaximumSize(QtCore.QSize(90, 50))
        self.button_sin.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_sin.setObjectName("button_sin")
        self.gridLayout.addWidget(self.button_sin, 0, 3, 1, 1)
        self.button_sec = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("sec("))
        self.button_sec.setMaximumSize(QtCore.QSize(90, 50))
        self.button_sec.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_sec.setObjectName("button_sec")
        self.gridLayout.addWidget(self.button_sec, 0, 4, 1, 1)
        self.button_arcsin = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("asin("))
        self.button_arcsin.setMaximumSize(QtCore.QSize(90, 50))
        self.button_arcsin.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_arcsin.setObjectName("button_arcsin")
        self.gridLayout.addWidget(self.button_arcsin, 0, 5, 1, 1)
        self.button_arcsec = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("asec("))
        self.button_arcsec.setMaximumSize(QtCore.QSize(90, 50))
        self.button_arcsec.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_arcsec.setObjectName("button_arcsec")
        self.gridLayout.addWidget(self.button_arcsec, 0, 6, 1, 1)
        self.button_pi = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("pi"))
        self.button_pi.setMaximumSize(QtCore.QSize(90, 50))
        self.button_pi.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_pi.setObjectName("button_pi")
        self.gridLayout.addWidget(self.button_pi, 1, 0, 1, 1)
        self.button_e = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("e"))
        self.button_e.setMaximumSize(QtCore.QSize(90, 50))
        self.button_e.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_e.setObjectName("button_e")
        self.gridLayout.addWidget(self.button_e, 1, 1, 1, 1)
        self.button_raiz = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("sqrt("))
        self.button_raiz.setMaximumSize(QtCore.QSize(90, 50))
        self.button_raiz.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_raiz.setObjectName("button_raiz")
        self.gridLayout.addWidget(self.button_raiz, 1, 2, 1, 1)
        self.button_cos = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("cos("))
        self.button_cos.setMaximumSize(QtCore.QSize(90, 50))
        self.button_cos.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_cos.setObjectName("button_cos")
        self.gridLayout.addWidget(self.button_cos, 1, 3, 1, 1)
        self.button_csc = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("csc("))
        self.button_csc.setMaximumSize(QtCore.QSize(90, 50))
        self.button_csc.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_csc.setObjectName("button_csc")
        self.gridLayout.addWidget(self.button_csc, 1, 4, 1, 1)
        self.button_arcos = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("acos("))
        self.button_arcos.setMaximumSize(QtCore.QSize(90, 50))
        self.button_arcos.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_arcos.setObjectName("button_arcos")
        self.gridLayout.addWidget(self.button_arcos, 1, 5, 1, 1)
        self.button_arccsc = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("acsc("))
        self.button_arccsc.setMaximumSize(QtCore.QSize(90, 50))
        self.button_arccsc.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_arccsc.setObjectName("button_arccsc")
        self.gridLayout.addWidget(self.button_arccsc, 1, 6, 1, 1)
        self.button_coma = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar(","))
        self.button_coma.setMaximumSize(QtCore.QSize(90, 50))
        self.button_coma.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_coma.setObjectName("button_coma")
        self.gridLayout.addWidget(self.button_coma, 2, 0, 1, 1)
        self.button_parent1 = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("("))
        self.button_parent1.setMaximumSize(QtCore.QSize(90, 50))
        self.button_parent1.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_parent1.setObjectName("button_parent1")
        self.gridLayout.addWidget(self.button_parent1, 2, 1, 1, 1)
        self.button_parent2 = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar(")"))
        self.button_parent2.setMaximumSize(QtCore.QSize(90, 50))
        self.button_parent2.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_parent2.setObjectName("button_parent2")
        self.gridLayout.addWidget(self.button_parent2, 2, 2, 1, 1)
        self.button_tan = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("tan("))
        self.button_tan.setMaximumSize(QtCore.QSize(90, 50))
        self.button_tan.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_tan.setObjectName("button_tan")
        self.gridLayout.addWidget(self.button_tan, 2, 3, 1, 1)
        self.button_cot = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("cot("))
        self.button_cot.setMaximumSize(QtCore.QSize(90, 50))
        self.button_cot.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_cot.setObjectName("button_cot")
        self.gridLayout.addWidget(self.button_cot, 2, 4, 1, 1)
        self.button_arctan = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("atan("))
        self.button_arctan.setMaximumSize(QtCore.QSize(90, 50))
        self.button_arctan.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_arctan.setObjectName("button_arctan")
        self.gridLayout.addWidget(self.button_arctan, 2, 5, 1, 1)
        self.button_arcot = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.presionar("acot("))
        self.button_arcot.setMaximumSize(QtCore.QSize(90, 50))
        self.button_arcot.setStyleSheet("font: 87 14pt \"Arial\";")
        self.button_arcot.setObjectName("button_arcot")
        self.gridLayout.addWidget(self.button_arcot, 2, 6, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setStyleSheet("QPushButton{\n"
"  padding: .375rem .75rem;\n"
"  border: 1px solid #00244b;\n"
"  border-radius: .25rem;\n"
"  color: #00244b;\n"
"  transition: color .15s ease-in-out,\n"
"  background-color .15s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #bed7e0;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_multi = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("*"))
        self.button_multi.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_multi.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_multi.setObjectName("button_multi")
        self.gridLayout_2.addWidget(self.button_multi, 2, 3, 1, 1)
        self.button_0 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("0"))
        self.button_0.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_0.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_0.setObjectName("button_0")
        self.gridLayout_2.addWidget(self.button_0, 3, 1, 1, 1)
        self.button_6 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("6"))
        self.button_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_6.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_6.setObjectName("button_6")
        self.gridLayout_2.addWidget(self.button_6, 1, 2, 1, 1)
        self.button_menos = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("-"))
        self.button_menos.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_menos.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_menos.setObjectName("button_menos")
        self.gridLayout_2.addWidget(self.button_menos, 1, 4, 1, 1)
        self.button_2 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("2"))
        self.button_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_2.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_2.setObjectName("button_2")
        self.gridLayout_2.addWidget(self.button_2, 2, 1, 1, 1)
        self.button_8 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("8"))
        self.button_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_8.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_8.setObjectName("button_8")
        self.gridLayout_2.addWidget(self.button_8, 0, 1, 1, 1)
        self.button_4 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("4"))
        self.button_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_4.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_4.setObjectName("button_4")
        self.gridLayout_2.addWidget(self.button_4, 1, 0, 1, 1)
        self.button_3 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("3"))
        self.button_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_3.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_3.setObjectName("button_3")
        self.gridLayout_2.addWidget(self.button_3, 2, 2, 1, 1)
        self.button_7 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("7"))
        self.button_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_7.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_7.setObjectName("button_7")
        self.gridLayout_2.addWidget(self.button_7, 0, 0, 1, 1)
        self.button_5 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("5"))
        self.button_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_5.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_5.setObjectName("button_5")
        self.gridLayout_2.addWidget(self.button_5, 1, 1, 1, 1)
        self.button_9 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("9"))
        self.button_9.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_9.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_9.setObjectName("button_9")
        self.gridLayout_2.addWidget(self.button_9, 0, 2, 1, 1)
        self.button_mas = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("+"))
        self.button_mas.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_mas.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_mas.setObjectName("button_mas")
        self.gridLayout_2.addWidget(self.button_mas, 1, 3, 1, 1)
        self.button_igual = QtWidgets.QPushButton(self.frame_7)
        self.button_igual.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_igual.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_igual.setObjectName("button_igual")
        self.gridLayout_2.addWidget(self.button_igual, 3, 2, 1, 1)
        self.button_punto = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("."))
        self.button_punto.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_punto.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_punto.setObjectName("button_punto")
        self.gridLayout_2.addWidget(self.button_punto, 3, 0, 1, 1)
        self.button_1 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("1"))
        self.button_1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_1.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_1.setObjectName("button_1")
        self.gridLayout_2.addWidget(self.button_1, 2, 0, 1, 1)
        self.button_div = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.presionar("/"))
        self.button_div.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_div.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_div.setObjectName("button_div")
        self.gridLayout_2.addWidget(self.button_div, 2, 4, 1, 1)
        self.button_del = QtWidgets.QPushButton(self.frame_7)
        self.button_del.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_del.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_del.setObjectName("button_del")
        self.gridLayout_2.addWidget(self.button_del, 0, 3, 1, 2)
        self.button_borrar = QtWidgets.QPushButton(self.frame_7)
        self.button_borrar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_borrar.setStyleSheet("font: 87 15pt \"Arial\";")
        self.button_borrar.setObjectName("button_borrar")
        self.gridLayout_2.addWidget(self.button_borrar, 3, 3, 1, 2)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_izquierdo)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_5.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(164, 188, 211, 0), stop:0.971591 rgba(255, 255, 255, 0));\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_derivada = QtWidgets.QPushButton(self.frame_5)
        self.button_derivada.setMaximumSize(QtCore.QSize(16777215, 35))
        self.button_derivada.setStyleSheet("QPushButton{\n"
"  padding: .375rem .75rem;\n"
"  border: 1px solid #00244b;\n"
"  border-radius: .25rem;\n"
"  color: #00244b;\n"
"  transition: color .15s ease-in-out,\n"
"  background-color .15s ease-in-out;\n"
"font: italic 14pt \"Arial Narrow\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #bed7e0;\n"
"font: italic 14pt \"Arial Narrow\";\n"
"}\n"
"")
        self.button_derivada.setObjectName("button_derivada")
        self.horizontalLayout_4.addWidget(self.button_derivada)
        self.button_integral = QtWidgets.QPushButton(self.frame_5)
        self.button_integral.setMaximumSize(QtCore.QSize(16777215, 35))
        self.button_integral.setStyleSheet("QPushButton{\n"
"  padding: .375rem .75rem;\n"
"  border: 1px solid #00244b;\n"
"  border-radius: .25rem;\n"
"  color: #00244b;\n"
"  transition: color .15s ease-in-out,\n"
"  background-color .15s ease-in-out;\n"
"font: italic 14pt \"Arial Narrow\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #bed7e0;\n"
"font: italic 14pt \"Arial Narrow\";\n"
"}\n"
"")
        self.button_integral.setObjectName("button_integral")
        self.horizontalLayout_4.addWidget(self.button_integral)
        self.button_integraldef = QtWidgets.QPushButton(self.frame_5)
        self.button_integraldef.setMaximumSize(QtCore.QSize(16777215, 35))
        self.button_integraldef.setStyleSheet("QPushButton{\n"
"  padding: .375rem .75rem;\n"
"  border: 1px solid #00244b;\n"
"  border-radius: .25rem;\n"
"  color: #00244b;\n"
"  transition: color .15s ease-in-out,\n"
"  background-color .15s ease-in-out;\n"
"font: italic 14pt \"Arial Narrow\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #bed7e0;\n"
"font: italic 14pt \"Arial Narrow\";\n"
"}\n"
"")
        self.button_integraldef.setObjectName("button_integraldef")
        self.horizontalLayout_4.addWidget(self.button_integraldef)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 2)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame_izquierdo)
        self.frame_derecho = QtWidgets.QFrame(self.centralwidget)
        self.frame_derecho.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_derecho.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(13, 156, 208, 241), stop:1 rgba(255, 255, 255, 255));")
        self.frame_derecho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_derecho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_derecho.setObjectName("frame_derecho")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_derecho)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.frame_derecho)
        self.frame.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(164, 188, 211, 0), stop:0.971591 rgba(255, 255, 255, 0));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setStyleSheet("\n"
"background-color: rgb(245, 245, 245)")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_derecho)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(164, 188, 211, 0), stop:0.971591 rgba(255, 255, 255, 0));\n"
"}\n"
"QLabel{\n"
"font: 75 14pt \"Arial Narrow\";\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_resp = QtWidgets.QLabel(self.frame_2)
        self.label_resp.setMaximumSize(QtCore.QSize(0, 0))
        self.label_resp.setText("")
        self.label_resp.setObjectName("label_resp")
        self.horizontalLayout_2.addWidget(self.label_resp)
        self.label_txt = QtWidgets.QLabel(self.frame_2)
        self.label_txt.setMaximumSize(QtCore.QSize(115, 16777215))
        self.label_txt.setStyleSheet("font: 75 13pt \"Arial Narrow\";")
        self.label_txt.setText("")
        self.label_txt.setObjectName("label_txt")
        self.horizontalLayout_2.addWidget(self.label_txt)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame_derecho)
        MainWindow.setCentralWidget(self.centralwidget)
        #CLASE SVG
        self.svg = QSvgWidget()
        self.horizontalLayout_2.addWidget(self.svg)

        #Llamadas a las funciones por medio de botones
        self.button_igual.clicked.connect(self.igual)
        self.button_del.clicked.connect(self.borrar)
        self.button_borrar.clicked.connect(self.label_entrada.clear)
        self.button_borrar.clicked.connect(self.borrargrafica)
        self.button_derivada.clicked.connect(self.derivada)
        self.button_integral.clicked.connect(self.integralindef)
        self.button_integraldef.clicked.connect(self.integraldef)
        self.button_derivada.clicked.connect(self.plot_widget)
        self.button_integral.clicked.connect(self.plot_widget) 
        self.iniciar_widget()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    #FUNCIONES
    # Asignar la tecla del boton
    def presionar(self,pressed):
            self.label_entrada.setText(f'{self.label_entrada.text()}{pressed}') 
            return pressed
    # Evaluar las valores matematicos     
    def igual(self):
        entrada = self.label_entrada.text()
        if entrada == "":
                self.validar_campovacio()
        else:        
                try:
                        ans = eval(entrada)
                        self.label_entrada.setText(str(ans))
                except:
                        self.validar()
    # Borrar los caracteres de la entrada de texto             
    def borrar(self):
        entrada = self.label_entrada.text()
        self.label_entrada.setText(entrada[:len(entrada)-1])  
    #FUNCIONES DE CALCULO
    def tex2svg(self,formula):
        self.fig = plt.figure(figsize=(0.5, 0.5))
        self.fig.text(5, 5, r'${}$'.format(formula),fontsize=20,
         color="blue",
         verticalalignment ='top', 
         horizontalalignment ='center',
         bbox ={'facecolor':'white', 
                'pad':800}
                )
        self.output = BytesIO()
        self.fig.savefig(self.output, dpi=300, format='svg', bbox_inches='tight', pad_inches=0.12,  facecolor ="w",  edgecolor ='b', orientation ='landscape')
        self.output.seek(0)
        return self.output.read()  
    # Integral definida
    def integraldef(self):
        espacio = self.label_entrada.text()
        entrada = espacio.replace('^','**')
        if entrada == "":
                self.validar_campovacio()
        else:        
                try:
                        c = self.label_entrada.text() #Entrada de texto
                        c1=c.split(',') #La expresion se separa por , (expresion, limite inferior, limite superior)
                        li=c1[1]
                        ls=c1[2]
                        inte=c1[0]
                        inte1 = sym.sympify(inte)
                        res = sym.integrate(inte1,('x',li,ls))
                        resl = sym.latex(res)
                        self.label_txt.setText("La respuesta es:")
                        self.label_resp.setText(str(res))
                        self.label_resp.hide()
                        self.svg.load(self.tex2svg(resl))
                        self.svg.show()
                except:
                        self.validar_integraldef() 
    #Integral Definida                    
    def integralindef(self):
        espacio = self.label_entrada.text()
        entrada = espacio.replace('^','**')
        if entrada == "":
                self.validar_campovacio()
        else:        
                try:
                        entrada_pant = self.label_entrada.text()
                        if 'x' in entrada_pant:
                                inte = self.label_entrada.text()
                                inte1 = sym.sympify(inte)
                                res = sym.integrate(inte1,('x',None,None))
                                resl = sym.latex(res)
                                self.label_txt.setText(str("La Integral es:"))
                                #Ocultar el label respt
                                self.label_resp.setText(str(res))
                                self.label_resp.hide()
                                self.svg.load(self.tex2svg(resl))
                                self.svg.show()
                        else:
                                inte = self.label_entrada.text()
                                inte1 = sym.sympify(inte)
                                res = sym.integrate(inte1,('y',None,None))
                                resl = sym.latex(res)
                                self.label_txt.setText(str("La Integral es:"))
                                #Ocultar el label respt
                                self.label_resp.setText(str(res))
                                self.label_resp.hide()
                                self.svg.load(self.tex2svg(resl))
                                self.svg.show()       
                except:
                        self.validar()
    #Funcion Derivada            
    def derivada(self):
        espacio = self.label_entrada.text()
        entrada = espacio.replace('^','**')
        if entrada == "":
                self.validar_campovacio()
        else:        
                try: 
                        entrada_pant = self.label_entrada.text()
                        if 'x' in entrada_pant:
                                d1= sym.sympify(entrada_pant)
                                r = sym.diff(d1,'x')
                                resl = sym.latex(r)
                                self.label_txt.setText(str("La derivada es:"))
                                #Ocultar el label respt
                                self.label_resp.setText(str(r))
                                self.label_resp.hide()
                                self.svg.load(self.tex2svg(resl))
                                self.svg.show()
                        else:
                                d1= sym.sympify(entrada_pant)
                                r = sym.diff(d1,'y')
                                resl = sym.latex(r)
                                self.label_txt.setText(str("La derivada es:"))
                                self.label_resp.setText(str(r))
                                self.label_resp.hide()
                                self.svg.load(self.tex2svg(resl))
                                self.svg.show()
                except:
                        self.validar()
                
    #FUNCIONES GRAFICAR
    # Borrar el contenido de la grafica
    def borrargrafica(self):
        self.label_resp.setText('')   
        self.label_txt.setText('') 
        hollowKnight = ""
        self.svg.load(hollowKnight)
        self.svg.show() 
        self.grafica.axis.clear() 
        self.widget.hide()
    #Iniciar la grafica    
    def iniciar_widget(self):
        self.grafica = MatploGraf()
        self.layoutvertical = QGridLayout()
        self.widget.setLayout(self.layoutvertical)
        self.layoutvertical.addWidget(self.grafica)
    #Dibujar los puntos de la grafica respecto a la funcion    
    def plot_widget(self):
        try:	
                self.grafica.axis.clear()
                expresion = self.label_entrada.text()
                expresion1 = sym.sympify(expresion)
                resl = sym.latex(expresion1)
                x = sym.Symbol('x')
                v = np.linspace(-15,15,100,endpoint=True)
                valores = []
                for i in range(len(v)):
                        c = ((expresion1).evalf(subs={x: v[i]}))
                        valores.append(c)
                self.grafica.axis.plot(v,valores,label=r"$" + f"{resl}" + r"$".format(expresion))
                self.grafica.canvas.draw() 
                
                expresionA = self.label_resp.text()
                f = self.label_resp.text()
                expresionB = sym.sympify(expresionA)
                res2 = sym.latex(expresionB)
                x = sym.Symbol('x')
                v = np.linspace(-15,15,100,endpoint=True)
                valores = []
                for i in range(len(v)):
                        c = ((expresionB).evalf(subs={x: v[i]}))
                        valores.append(c)
                self.grafica.axis.plot(v,valores,label=r"$" + f"{res2}" + r"$".format(expresionA))
                self.grafica.axis.legend(loc = 'upper left')
                self.grafica.canvas.draw() 	
                self.widget.show()
        except:
                pass


#VALIDACIONES
    def validar_integraldef(self):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Warning)
        msg.setText("Expresion Invalida")
        msg.setInformativeText("Colocar correctamente los limites")
        msg.setWindowTitle("Error expresion Invalida")
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok  | QtWidgets.QMessageBox.Cancel)
        msg.exec_()               

    def validar_campovacio(self):
        entrada = self.label_entrada.text()
        if entrada == "":
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Warning)
            msg.setText("Campos Vacios")
            msg.setInformativeText("Ingresar datos")
            msg.setWindowTitle("Campos vacios")
            #msg.setDetailedText("The details are as follows:")
            msg.setStandardButtons(QtWidgets.QMessageBox.Ok  | QtWidgets.QMessageBox.Cancel)
            msg.exec_()   

    def validar(self):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Warning)
        msg.setText("ERROR")
        msg.setInformativeText("Expresion no valida!")
        msg.setWindowTitle("Error expresion Invalida")
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok  | QtWidgets.QMessageBox.Cancel)
        msg.exec_()     

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Calculadora P-C", "Calculadora P-C"))
        self.button_y.setText(_translate("MainWindow", "y"))
        self.button_y.setShortcut(_translate("MainWindow", "Y"))
        self.button_exp.setText(_translate("MainWindow", "x^"))
        self.button_exp.setShortcut(_translate("MainWindow", "^"))
        self.button_cot.setText(_translate("MainWindow", "cot"))
        self.button_e.setText(_translate("MainWindow", "e"))
        self.button_pi.setText(_translate("MainWindow", "π"))
        self.button_raiz.setText(_translate("MainWindow", "√"))
        self.button_sin.setText(_translate("MainWindow", "sin"))
        self.button_x.setText(_translate("MainWindow", "x"))
        self.button_x.setShortcut(_translate("MainWindow", "x"))
        self.button_cos.setText(_translate("MainWindow", "cos"))
        self.button_sec.setText(_translate("MainWindow", "sec"))
        self.button_csc.setText(_translate("MainWindow", "csc"))
        self.button_tan.setText(_translate("MainWindow", "tan"))
        self.button_arcsin.setText(_translate("MainWindow", "arcsin"))
        self.button_arcsec.setText(_translate("MainWindow", "arcsec"))
        self.button_arcos.setText(_translate("MainWindow", "arccos"))
        self.button_arccsc.setText(_translate("MainWindow", "arccsc"))
        self.button_arctan.setText(_translate("MainWindow", "arctan"))
        self.button_arcot.setText(_translate("MainWindow", "arccot"))
        self.button_parent2.setText(_translate("MainWindow", ")"))
        self.button_parent2.setShortcut(_translate("MainWindow", ")"))
        self.button_parent1.setText(_translate("MainWindow", "("))
        self.button_parent1.setShortcut(_translate("MainWindow", "("))
        self.button_coma.setText(_translate("MainWindow", ","))
        self.button_coma.setShortcut(_translate("MainWindow", ","))
        self.button_multi.setText(_translate("MainWindow", "*"))
        self.button_multi.setShortcut(_translate("MainWindow", "*"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_0.setShortcut(_translate("MainWindow", "0"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_6.setShortcut(_translate("MainWindow", "6"))
        self.button_menos.setText(_translate("MainWindow", "-"))
        self.button_menos.setShortcut(_translate("MainWindow", "-"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_2.setShortcut(_translate("MainWindow", "2"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_8.setShortcut(_translate("MainWindow", "8"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_4.setShortcut(_translate("MainWindow", "4"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_3.setShortcut(_translate("MainWindow", "3"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_7.setShortcut(_translate("MainWindow", "7"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_5.setShortcut(_translate("MainWindow", "5"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_9.setShortcut(_translate("MainWindow", "9"))
        self.button_mas.setText(_translate("MainWindow", "+"))
        self.button_mas.setShortcut(_translate("MainWindow", "+"))
        self.button_igual.setText(_translate("MainWindow", "="))
        self.button_igual.setShortcut(_translate("MainWindow", "Enter"))
        self.button_punto.setText(_translate("MainWindow", "."))
        self.button_punto.setShortcut(_translate("MainWindow", "."))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_1.setShortcut(_translate("MainWindow", "1"))
        self.button_div.setText(_translate("MainWindow", "/"))
        self.button_div.setShortcut(_translate("MainWindow", "/"))
        self.button_del.setText(_translate("MainWindow", "🠔"))
        self.button_del.setShortcut(_translate("MainWindow", "Backspace"))
        self.button_borrar.setText(_translate("MainWindow", "AC"))
        self.button_derivada.setText(_translate("MainWindow", "ƒ\'(x)"))
        self.button_integral.setText(_translate("MainWindow", "∫"))
        self.button_integraldef.setText(_translate("MainWindow", "∫nⁿ"))

class MatploGraf(QtWidgets.QWidget):
	def __init__(self,parent=None):
		super(MatploGraf,self).__init__(parent)
		self.figure = Figure()
		self.canvas = FigureCanvasQTAgg(self.figure)
		self.axis = self.figure.add_subplot(111)
		self.toolbar = NavigationToolbar(self.canvas, self)

		self.layoutvertical = QVBoxLayout(self)
		self.layoutvertical.addWidget(self.canvas)
		self.layoutvertical.addWidget(self.toolbar)

def iconodesdeBase64(base64):
        pixmap = QPixmap()
        pixmap.loadFromData(QByteArray.fromBase64(base64))
        icon = QIcon(pixmap)
        return icon
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
